test_that("arrange_cols_omv works", {
    nmeInp <- paste0(tempfile(), ".rds")
    nmeOut <- paste0(tempfile(), "_A.omv")
    saveRDS(jmvReadWrite::AlbumSales, nmeInp)

    arrange_cols_omv(nmeInp, nmeOut, varOrd = c("selSbj", "Sales", "Adverts", "Airplay", "Image"))
    expect_true(file.exists(nmeOut))
    expect_gt(file.info(nmeOut)$size, 1)
    expect_true(chkFle(nmeOut, isZIP = TRUE))
    expect_true(chkFle(nmeOut, fleCnt = "meta"))
    expect_true(chkFle(nmeOut, fleCnt = "metadata.json"))
    expect_true(chkFle(nmeOut, fleCnt = "data.bin"))

    dtaFrm <- read_omv(nmeOut, sveAtt = FALSE)
    expect_s3_class(dtaFrm, "data.frame")
    expect_equal(dim(dtaFrm), c(200, 5))
    expect_equal(names(dtaFrm), c("selSbj", "Sales", "Adverts", "Airplay", "Image"))
    expect_equal(as.vector(sapply(dtaFrm, typeof)), c("integer", "integer", "double", "integer", "integer"))
    unlink(nmeOut)

    arrange_cols_omv(nmeInp, nmeOut, varMve = list(Sales = -3, Adverts = 2))
    dtaFrm <- read_omv(nmeOut, sveAtt = FALSE)
    expect_s3_class(dtaFrm, "data.frame")
    expect_equal(dim(dtaFrm), c(200, 5))
    expect_equal(names(dtaFrm), c("selSbj", "Sales", "Adverts", "Airplay", "Image"))
    expect_equal(as.vector(sapply(dtaFrm, typeof)), c("integer", "integer", "integer", "integer", "double"))
    unlink(nmeOut)

# test cases for psvAnl

    # test cases for code coverage ============================================================================================================================
    expect_error(arrange_cols_omv(nmeInp, nmeOut))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varOrd = list()))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varOrd = c()))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varOrd = c(1, 2)))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varOrd = c("", "")))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varMve = c()))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varMve = list()))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varMve = list(1, 1)))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varMve = list(A = "1", B = "1")))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varMve = list(A = 1, B = 1.1)))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varMve = list(A = 1, B = 0)))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varOrd = c("Sale", "Adverts", "Airplay", "Image")))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varMve = list(Sale = -3)))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varMve = list(Sales = -5)))
    expect_false(file.exists(nmeOut))
    expect_error(arrange_cols_omv(nmeInp, nmeOut, varMve = list(Sales = -3, Image = 2)))
    expect_false(file.exists(nmeOut))

    expect_warning(arrange_cols_omv(nmeInp, nmeOut, varOrd = c("Sales", "Adverts", "Airplay", "Image")))
    expect_true(file.exists(nmeOut))
    unlink(nmeOut)
    expect_warning(arrange_cols_omv(nmeInp, nmeOut, varOrd = c("Sales", "Adverts", "Airplay", "Image"), varMve = list(Sales = -3)))
    expect_true(file.exists(nmeOut))
    unlink(nmeOut)

    unlink(nmeInp)
})
