# Run CI for R using https://eddelbuettel.github.io/r-ci/

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  _R_CHECK_FORCE_SUGGESTS_: "false"

jobs:
  ci:
    strategy:
      matrix:
        include:
          - { name: container, os: ubuntu-latest, container: rocker/r2u4ci }
          - { name: r-devel,   os: ubuntu-latest, container: rocker/drd }
          - { name: macos,     os: macos-latest }
          - { name: ubuntu,    os: ubuntu-latest }

    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}

    steps:
      - uses: actions/checkout@v6

      - name: Setup
        uses: eddelbuettel/github-actions/r-ci@master

      - name: Dependencies
        run: ./run.sh install_all

      - name: Test
        run: ./run.sh run_tests

      #- name: Logs
      #  run: ./run.sh dump_logs
      #  if: failure()
        
      #- name: Coverage
      #  if: ${{ matrix.os == 'ubuntu-latest' }}
      #  run: ./run.sh coverage
      #  env:
      #    CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
